### ISSUE TITLE
PCExhumed: missing explosion sounds

### ISSUE THREAD

**Issue by BSzili** [nukeykt/NBlood#365]
Neither the grenades nor those flaming pots have sounds effects when they explode. Very rarely I hear their sound, but 99% of the time they are completely silent when blowing up.

**Comment by MexMeRcUrY** [comment]
BSZili, Please check your files there must be something missing. I was not able to replicate the issue in the latest version.

**Comment by MexMeRcUrY** [comment]
I was not able to replicate your issue in the latest 32bit version ... please download the latest version from :
https://lerppu.net/wannabethesis/

**Comment by BSzili** [comment]
For me it's happening with the latest 32-bit version as well.

**Comment by sirlemonhead** [comment]
It's due to the distance calculation the game does when determining the volume for sounds. It improves if you raise the ingame volume slider up to full (and then balance down in your OS volume setting)

I'm working on fixing it - I have it a lot better but it's still kinda crappy (there's a harsh change between hearing a sound and not hearing a sound - you barely move backwards but it's considered enough distance that the sound cuts off completely)

**Comment by BSzili** [comment]
Thanks for the heads up, I suspected it was some kind of volume attenuation issue.
