### ISSUE TITLE
[Feature Request] Support for Duke Nukem spinoffs games in the far future?

### ISSUE THREAD

**Issue by John-Enigma** [nukeykt/NBlood#388]
Since nBlood recently got Duke Nukem 64 support, is it possible for other DN games to get the same treatment sometime in the future, like Zero Hour, Time To Kill, The Land of Babes, and Advance?

The only ones that I don't mention are Project Manhattan and Critical Mass, since one is a 2.5D platformer reminiscent of the first two Duke Nukem games, and the other one is a run and gun type game that is very different from your typical DN3D game, had a canceled PSP version (and the Library of Congress has the src), and is in legal limbo (like some Duke Nukem games).

I don't mention Total Meltdown either because I don't know what's the consensus of that port among fans. Nor if there are plans for this one to get nBlood support too right after 64.

That is all.

Do you guys think it's possible? Or is it not worth it?

**Comment by CommonLoon102** [comment]
Zero Hour, Time To Kill and The Land of Babes are using a completely different engine. Maybe porting the Advance version would be possible but it is quite different too.

**Comment by Dzierzan** [comment]
I doubt Advance uses Build engine either. it would probably better to just recreate maps or weapons in eduke32 than making a port of it.

**Comment by Hendricks266** [comment]
Zero Hour is a derived from Duke Nukem 64 and therefore, besides Total Meltdown, it is the only one eligible for inclusion. The rest have no technological relation to Duke 3D or Build and are not even under consideration.

The addition of future games entirely depends on developer interest. Zero Hour shares the DN64 renderer, the Build collision code, and some data formats, but the game code is largely unique.

Closing this issue because pie in the sky feature requests are not a welcome use of the issue tracker. See #280.

**Comment by CommonLoon102** [comment]
Total Meltdown is basically the same as the DOS version, except it has some new music, but those can be ripped and played as oggs instead of the original midis. Also it has 6 new levels (in a new 4th episode) with a few new types of monsters, but that's all. So maybe the PS1 version (Total Meltdown) could be played with NBlood as it is not that different from the DOS version.

**Comment by nukeykt** [comment]
ZH is only game that i'm interested in, but that'd take too much time, so it is not gonna happen

**Comment by SilentMRG** [comment]
Hello everybody...

Taking advantage of the subject...

Rednukem have support for these expansions: "Duke it out in DC; Duke Caribbean: Life's a Beach and Duke: Nuclear Winter"??? I don't think so... So it would be a good idea to add this additional content to the Rednukem list.

Thanks... =)
